// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import * as dotenvExpand from 'dotenv-expand';
import * as dotenv from 'dotenv';
import { defineConfig } from 'prisma/config';

dotenvExpand.expand(dotenv.config());

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['POSTGRES_URI'],
  },
});
